<?xml version="1.0"?>
<package format="3">
  <name>luna_linaks</name>
  <version>0.1.0</version>
  <description>LINAK Techline CAN SAE J1939 linear actuator driver</description>
  <maintainer email="pskoczylas04@gmail.com">piotr</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
