# fiducial_localizer params (Jetson / default)
marker_localizer:
  ros__parameters:
    image_topic: '/camera/image_raw'
    camera_info_topic: '/camera/camera_info'
    aruco_dict: 'DICT_4X4_50'
    marker_id: -1
    marker_size_m: 0.16
    world_frame: 'world'
    robot_frame: 'robot'
    world_to_marker_xyz: [0.0, 0.63, 0.0]
    world_to_marker_yaw: 0.0
    camera_to_robot_xyz: [0.0, 0.0, 0.0]
    camera_to_robot_yaw: 0.0
    fx: 0.0
    fy: 0.0
    cx: 0.0
    cy: 0.0
