
// Copyright 2020 PAL Robotics S.L.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Author: Bence Magyar, Enrique Fernández, Manuel Meraz
 */

/*
 * This code has been adapted and/or modified for use in the 2024-25 WPI Lunabotics MQP.
 * Author: Sam Rooney
 */

#ifndef LUNA_CONTROL__LUNA_CONTROLLER_HPP_
#define LUNA_CONTROL__LUNA_CONTROLLER_HPP_

#include <chrono>
#include <cmath>
#include <memory>
#include <queue>
#include <string>
#include <vector>

// Ros2 Controler API
#include "controller_interface/controller_interface.hpp"
// Internal helper components (look at this code later)
#include "luna_control/odometry.hpp"
#include "luna_control/speed_limiter.hpp"

// message types. 
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "odometry.hpp" //dupicate of above?

#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.h"
#include "realtime_tools/realtime_publisher.h"
#include "tf2_msgs/msg/tf_message.hpp"

// auto-generated by generate_parameter_library
#include "luna_controller_parameters.hpp"

namespace luna_controller
{

    // For convenience redefine commonly used message types
    using Twist = geometry_msgs::msg::TwistStamped;

    // Main Class of control package. Inherits from ControllerInterface base class
    class LunaController : public controller_interface::ControllerInterface
    {
    public:
        // Constructor
        LunaController();

        // Controller Interface methods
        // tell ROS2 what joint interfaces are needed. 
        controller_interface::InterfaceConfiguration command_interface_configuration() const override;

        controller_interface::InterfaceConfiguration state_interface_configuration() const override;

        // declare a function called update that returns controller_interface::return_type
        // and takes two parameters: a constant reference to rclcpp::Time named time,
        // and a constant reference to rclcpp::Duration named period.
        controller_interface::return_type update(
            const rclcpp::Time &time, const rclcpp::Duration &period) override;


        // functions for each lifecycle transition
        // these are called automatically by the lifecycle manager

        // on_init implementation
        // called when the controller is created
        // loads the parameters using the parameter listener
        controller_interface::CallbackReturn on_init() override;

        // on_configure implementation
        // called when the controller is configured
        // sets up publishers and subscribers, configures odometry - sets up other paraemeters. 
        controller_interface::CallbackReturn on_configure(
            const rclcpp_lifecycle::State &previous_state) override;

        // on_activate implementation
        // called when the controller is activated
        // action is unclear in code - likely resets odometry and timestamps.
        controller_interface::CallbackReturn on_activate(
            const rclcpp_lifecycle::State &previous_state) override;

        // on_deactivate implementation
        // called when the controller is deactivated
        // action is unclear in code - likely halts the robot. (calls the clear fucntion for every handle)
        controller_interface::CallbackReturn on_deactivate(
            const rclcpp_lifecycle::State &previous_state) override;

        // on_cleanup implementation
        // called when the controller is cleaned up
        // calls received_velocity_msg_ptr_.set(std::make_shared<Twist>());
            // likely resets the controller to a clean state.
        controller_interface::CallbackReturn on_cleanup(
            const rclcpp_lifecycle::State &previous_state) override;

        // on_error implementation
        // called when the controller enters an error state
        // calls reset() - likely resets the controller to a clean state.
        // if reset fails, returns ERROR
        controller_interface::CallbackReturn on_error(
            const rclcpp_lifecycle::State &previous_state) override;

        // on_shutdown implementation
        // called when the controller is shutdown
        // calls a halt() function - likely stops the robot.
        controller_interface::CallbackReturn on_shutdown(
            const rclcpp_lifecycle::State &previous_state) override;
    // return controller_interface::return_type::OK;

    // define protected members 
    protected:
        // Define handle structures for wheels and pods
        // these hold references to the command and feedback interfaces for each wheel/pod
        // can call .get() on the reference wrappers to get the actual interface
            // .get().set_value(...) to set command values (get acquires the reference, set sends a value to it)
        struct WheelHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> feedback;
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> velocity;
        };

        struct PodHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> feedback;
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> position;
        };

        // Functions to configure wheel and pod segments
        // called in on_configure to set up the handles for each wheel and pod
        // parameters: 
            // segment: string name of the segment (e.g. "left_back_wheel")
            // wheel_names/pod_names: vector of strings with the names of the joints in the segment
            // registered_handles: vector to store the configured handles
        // i.e. : configure_wheel_segment("right_front", params_.right_front_wheel_names, registered_right_front_wheel_handles_);
        controller_interface::CallbackReturn configure_wheel_segment(
            const std::string &segment, const std::vector<std::string> &wheel_names,
            std::vector<WheelHandle> &registered_handles);

        controller_interface::CallbackReturn configure_pod_segment(
            const std::string &segment, const std::vector<std::string> &pod_names,
            std::vector<PodHandle> &registered_handles);

        // Member variables
        // Vectors of handles for each wheel and pod segment
        // DYNAMIC ARRAYS to support multiple wheels/pods per side
        // 8 TOTAL VECTORS FOR 8 JOINT TYPES
        std::vector<WheelHandle> registered_left_back_wheel_handles_;
        std::vector<WheelHandle> registered_right_back_wheel_handles_;
        std::vector<WheelHandle> registered_left_front_wheel_handles_;
        std::vector<WheelHandle> registered_right_front_wheel_handles_;

        std::vector<PodHandle> registered_left_back_pod_handles_;
        std::vector<PodHandle> registered_right_back_pod_handles_;
        std::vector<PodHandle> registered_left_front_pod_handles_;
        std::vector<PodHandle> registered_right_front_pod_handles_;


        // Parameters from ROS for diff_drive_controller
        std::shared_ptr<luna_controller::ParamListener> param_listener_;
        Params params_;
        /* Number of wheels on each side of the robot. This is important to take the wheels slip into
         * account when multiple wheels on each side are present. If there are more wheels then control
         * signals for each side, you should enter number for control signals. For example, Husky has two
         * wheels on each side, but they use one control signal, in this case '1' is the correct value of
         * the parameter. */
        int wheels_per_side_;

        Odometry odometry_;

        // Timeout to consider cmd_vel commands old
        std::chrono::milliseconds cmd_vel_timeout_{500};

        // odometry publishers 
        // publish odometry and tf messages on "~/odom" and "/tf" topics
        //publisher for nav_msgs::msg::Odometry
        std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
        // realtime publisher for nav_msgs::msg::Odometry
        // realtime means it can be called from the realtime update loop
        // non-blocking method to publish messages
        std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
            realtime_odometry_publisher_ = nullptr;

        // publisher for tf2_msgs::msg::TFMessage
        std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
            nullptr;
        // realtime publisher for tf2_msgs::msg::TFMessage
        std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
            realtime_odometry_transform_publisher_ = nullptr;

        // Subscriber for velocity commands
        bool subscriber_is_active_ = false;
        rclcpp::Subscription<Twist>::SharedPtr velocity_command_subscriber_ = nullptr;

        // Realtime buffer to store the last received velocity command
        realtime_tools::RealtimeBox<std::shared_ptr<Twist>> received_velocity_msg_ptr_{nullptr};

        //store previous commands to understand derivatives acceleration etc. 
        std::queue<Twist> previous_commands_; // last two commands

        // instances of speed limiters for linear, strafe and angular velocities
        SpeedLimiter limiter_linear_;
        SpeedLimiter limiter_strafe_;
        SpeedLimiter limiter_angular_;

        // whether to publish limited velocity commands
        bool publish_limited_velocity_ = false;
        // publisher for limited velocity commands
        std::shared_ptr<rclcpp::Publisher<Twist>> limited_velocity_publisher_ = nullptr;
        // realtime publisher for limited velocity commands
        std::shared_ptr<realtime_tools::RealtimePublisher<Twist>> realtime_limited_velocity_publisher_ =
            nullptr;

        rclcpp::Time previous_update_timestamp_{0};

        // publish rate limiter
        double publish_rate_ = 50.0;
        rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
        rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

        bool is_halted = false;

        bool reset();
        void halt();
    };

} // namespace luna_control

#endif // LUNA_CONTROL__LUNA_CONTROLLER_HPP_
